[unstable]
build-std = ["core", "compiler_builtins"]

[build]
target = "aarch64-unknown-none.json"

[target.'cfg(target_os = "none")']
runner = "qemu-system-aarch64 -machine virt -m 1024M -cpu cortex-a53 -serial file:./guest.log -kernel"
